name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true

      - name: Install dependencies
        run: |
          pdm install

      - name: Run ruff
        run: |
          pdm run ruff check .

      - name: Run mypy
        run: |
          pdm run mypy .

      - name: Run tests
        run: |
          pdm run pytest
